language: node_js
node_js:
 - "node"

cache: npm

script: 
-   npm i
-   npm run docs:build

deploy:
 provider: pages
 skip_cleanup: true
 local_dir: docs/.vuepress/dist
 github_token: $GH_TOKEN
 local_dir: dist
 on:
   branch: master