language: node_js
node_js:
 - "node"

cache: npm

before_install:
  - npm install
script: 
-   npm run docs:build

deploy:
 provider: pages
 skip_cleanup: true
 local_dir: docs/.vuepress/dist
 github_token: $GH_TOKEN
 keep-history: true
 on:
   branch: master